apiVersion: v1
kind: Namespace
metadata:
  name: nauka

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pro
  namespace: nauka
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: nginx-pro
  template:
    metadata:
      labels:
        app: nginx-pro
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: moja-strona-html

---        

apiVersion: v1
kind: Service
metadata:
  name: nginx-pro-service
  namespace: nauka
spec:
  type: NodePort
  selector:
    app: nginx-pro
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090
