apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: kube-system  # Wrzucamy to do systemowego namespace
  labels:
    app: cloudflared
spec:
  replicas: 2             # Dwa tunele dla High Availability! (Jak jeden padnie, drugi działa)
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        - --token
        - eyJhIjoiMjQ3OWQxMzNkMGM2YzRiOWE5NGI0ZDRlNzcxMzJiMTQiLCJ0IjoiMWQ4NTg1ZGQtYWZiOS00NDkzLWIxYTItMmY5YTJkZTZjN2ZkIiwicyI6IlpUYzFOV1psTkdFdE5tWmtOQzAwWXpKbExXRTFOVEV0TmpsaVpHVXhZV0UyWWpFMCJ9
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
